### ISSUE TITLE
请问单应矩阵归一化

### ISSUE THREAD

**Issue by yulongshan** [zhaitianyong/CameraCalibration#1]
1、请问您这里单应矩阵归一化算法原理是参考什么资料的，和ORB-SLAM中和MVG中的原理似乎都不一致，麻烦您指教下！
2、还有DLT求解单应矩阵时，input ( 2*i+1, 7 ) = -srcNormal ( i, 0 ) * dstNormal ( i, 1 ); 这里应该也是dstNormal ( i, 0 )吧。

**Comment by zhaitianyong** [comment]
您好，
   一直没有查看邮箱，今天看到你提的问题，谢谢。

1. 对第一个问题，数据去中心化应该都一样的，对于尺度问题，我主要分别计算了x' 和 y'的标准差，然后把样本数据规划到以根方2为半径的圆内。所以就用scale = 根方2/标准差，我也又看到用1/标准差的，其实结果都一样。
 ORB_SLAM2 可能为了计算方便，不需要计算标准差，就用绝对值的和的平均代替。
2. 我程序的公式确实有些问题，
input ( 2*i+1, 7 ) = -srcNormal ( i, 0 ) * dstNormal ( i, 1 );
应该修改为 
input ( 2*i+1, 7 ) = -srcNormal ( i, 1 ) * dstNormal ( i, 0 );



在此非常感谢你的邮件，谢谢。有问题可以交流
------------------------------------------------------------------


发件人：yulongshan <notifications@github.com>
发送时间：2020年7月17日(星期五) 10:15
收件人：zhaitianyong/CameraCalibration <CameraCalibration@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[zhaitianyong/CameraCalibration] 请问单应矩阵归一化 (#1)

1、请问您这里单应矩阵归一化算法原理是参考什么资料的，和ORB-SLAM中和MVG中的原理似乎都不一致，麻烦您指教下！
 2、还有DLT求解单应矩阵时，input ( 2*i+1, 7 ) = -srcNormal ( i, 0 ) * dstNormal ( i, 1 ); 这里应该也是dstNormal ( i, 0 )吧。

**Comment by yulongshan** [comment]
十分感谢！



发自我的小米手机
在 atway <notifications@github.com>，2020年8月18日 10:23写道：

您好，
一直没有查看邮箱，今天看到你提的问题，谢谢。

1. 对第一个问题，数据去中心化应该都一样的，对于尺度问题，我主要分别计算了x' 和 y'的标准差，然后把样本数据规划到以根方2为半径的圆内。所以就用scale = 根方2/标准差，我也又看到用1/标准差的，其实结果都一样。
ORB_SLAM2 可能为了计算方便，不需要计算标准差，就用绝对值的和的平均代替。
2. 我程序的公式确实有些问题，
input ( 2*i+1, 7 ) = -srcNormal ( i, 0 ) * dstNormal ( i, 1 );
应该修改为
input ( 2*i+1, 7 ) = -srcNormal ( i, 1 ) * dstNormal ( i, 0 );



在此非常感谢你的邮件，谢谢。有问题可以交流
------------------------------------------------------------------


发件人：yulongshan <notifications@github.com>
发送时间：2020年7月17日(星期五) 10:15
收件人：zhaitianyong/CameraCalibration <CameraCalibration@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[zhaitianyong/CameraCalibration] 请问单应矩阵归一化 (#1)

1、请问您这里单应矩阵归一化算法原理是参考什么资料的，和ORB-SLAM中和MVG中的原理似乎都不一致，麻烦您指教下！
2、还有DLT求解单应矩阵时，input ( 2*i+1, 7 ) = -srcNormal ( i, 0 ) * dstNormal ( i, 1 ); 这里应该也是dstNormal ( i, 0 )吧。
